trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build .NET Core API
  jobs:
  - job: Build
    displayName: Build Job
    steps:

    - script: dotnet --info
      displayName: Check .NET SDK Installed

    - script: dotnet restore
      displayName: Restore Packages

    - script: dotnet build --configuration $(buildConfiguration) --no-restore
      displayName: Build Project

    - script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: Publish Project

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'