trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet --info
  displayName: Check DotNet SDK

- script: dotnet nuget list source
  displayName: Show NuGet Sources

- script: dotnet nuget locals all --clear
  displayName: Clear NuGet Cache

- script: dotnet restore EmployeeApiWithEmployeeSalary.sln
  displayName: Restore Packages

- script: dotnet build EmployeeApiWithEmployeeSalary.sln --configuration $(buildConfiguration) --no-restore
  displayName: Build Project

- script: dotnet publish EmployeeApiWithEmployeeSalary/EmployeeApiWithEmployeeSalary.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Publish Project
- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    azureSubscription: 'Azure-ServiceConnection'
    appType: 'webApp'
    appName: 'testapi01'
    package: '$(Build.ArtifactStagingDirectory)'